---
title: "Syllabus"
---



## Course info

|           | Day       | Time              | Location |
|-----------|-----------|-------------------|----------|
| Lecture   | Monday    | 08:15  - 09:45 am  |  [016b](https://horst.hdm-stuttgart.de/016b)  |


:::{.callout-important}
Note that there are additional lectures (see schedule at [StarPlan](https://splan.hdm-stuttgart.de/splan/))
:::

## Learning objectives

By the end of this module, students are able to: <br>

- Effectively plan and execute market research projects <br>
- Conduct experiments and A/B tests <br> 
- Use predictive models and clustering methods <br>
- Utilize modern tools and technologies for data analysis <br>
- Clearly and effectively communicate results <br>


## Where to get help

- If you have a question during lecture, feel free to ask it! 
- Outside of class, any general questions about course content or assignments should be posted on the Moodle course forum.
- Emails should be reserved for questions not appropriate for the public forum. **If you email me, please include the name of our course in the subject line.** 

Check out the [Support](course-support.qmd) page for more resources.

## Textbooks

This course is mainly based on the following resources:

[Çetinkaya-Rundel, M. & Hardin, J (2023). Introduction to Modern Statistics. OpenIntro. Inc.](https://openintro-ims.netlify.app/)

[James, G., Witten, D., Hastie, T., Tibshirani, R. & Taylor, J. (2023). An Introduction to Statistical Learning with Python. New York: Springer.](https://www.statlearning.com/)

[Lau, S., Gonzalez, J. & Nolan, D. (2023). Learning Data Science. O'Reilly Media, Inc.](https://learningds.org/intro.html)


## Exam {#sec-exams}

There will be one exam at the end of the semester. 

